### PR TITLE
Fixes retrieval of version string from source files doc blocks (fixes #36)

### LINKED ISSUE #36: Suggested improvement to command retrieving version number
Summary:

When running this command and using the plugin header example described in the WordPress Plugin handbook, the version number is not found and therefore not appended to the zip archive.

Steps to reproduce:

1. Create plugin using plugin header format described in the WordPress Plugin handbook - https://developer.wordpress.org/plugins/the-basics/header-requirements/
1. Run `wp dist-archive` command to create plugin archive

Because the Version in the header example does not have the trailing asterisk, the version number is not found in the plugin header.

As per this slack conversation around the issue - https://wordpress.slack.com/archives/C02RP4T41/p1547804432280500
@swissspidy suggested reusing/extracting the header parsing functionality used by the i18n command in core
@schlessera suggested it might be time to extract that to a `get_file_header` helper method, or similar.

### PR DESCRIPTION
**Pull request by santilin**
In the issue there is a suggestion to refactor code from the `i18n` command. However, the code in the `i18n` command can't be used as is because it only handles functions, and the `plugin.php` header doesn't have to have a function on it.

I have replaced the former `preg_match` on the contents of all the php files in the plugin into a more sophisticated way of extracting the version tag:

* Use php's `token_get_all` to parse the php file
* For each `doc_block`, parse it to get all the tags
* return the `version` tag.

It's worth noting that the tags might be specified as @version or Version: and that a leading * might be in the line.

### CODE REVIEW

**Comment by schlessera** [comment]
@santilin Before I do a line-by-line review of the code, can you please push a commit to fix the indentation, it seems to be all over the place.
According to WPCS, please use tabs for indentation, and spaces for alignment only.

**Comment by santilin** [comment]
I think this PR is ready for merging

**Comment by santilin** [comment]
> @santilin Before I do a line-by-line review of the code, can you please push a commit to fix the indentation, it seems to be all over the place.
> According to WPCS, please use tabs for indentation, and spaces for alignment only.

Done

File: src/Dist_Archive_Command.php [hunk 1]
```diff
@@ -92,8 +92,9 @@ public function __invoke( $args, $assoc_args ) {
 		$version = '';
 		foreach ( glob( $path . '/*.php' ) as $php_file ) {
 			$contents = file_get_contents( $php_file, false, null, 0, 5000 );
-			if ( preg_match( '#\* Version:(.+)#', $contents, $matches ) ) {
-				$version = '.' . trim( $matches[1] );
+			$version = $this->get_version_in_code($contents);
+			if( ! empty( $version ) ) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			if ( ! empty( $version ) ) {
```

File: src/Dist_Archive_Command.php [hunk 2]
```diff
@@ -92,8 +92,9 @@ public function __invoke( $args, $assoc_args ) {
...
+				$version = '.' . trim($version);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
				$version = '.' . trim( $version );
```

File: src/Dist_Archive_Command.php [hunk 3]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
 			mkdir( $directory, $mode = 0777, $recursive = true );
 		}
 	}
+
+	/**
+	 * Gets the content of a version tag in any doc block in the given source code string
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * Gets the content of a version tag in any doc block in the given source code string.
```

File: src/Dist_Archive_Command.php [hunk 4]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * The version tag might be specified as @version x.y.z or Version: x.y.z and it might be preceeded by an *
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * The version tag might be specified as "@version x.y.z" or "Version: x.y.z" and it can
	 * be preceded by an asterisk (*).
```

File: src/Dist_Archive_Command.php [hunk 5]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * @param string $code_str the source code string to look into
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @param string $code_str The source code string to look into.
```

File: src/Dist_Archive_Command.php [hunk 6]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 * @return null|string the version string
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @return null|string The detected version string.
```

File: src/Dist_Archive_Command.php [hunk 7]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 */
+	private static function get_version_in_code($code_str)
+	{
+		$tokens = array_values(
+			array_filter(
+				token_get_all($code_str),
+				function ($token) {
+					return !is_array($token) || $token[0] !== T_WHITESPACE;
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
					return ! is_array($token) || $token[0] !== T_WHITESPACE;
```

File: src/Dist_Archive_Command.php [hunk 8]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * @param string $code_str the source code string to look into
+	 * @return null|string the version string
+	 */
+	private static function get_version_in_code($code_str)
+	{
+		$tokens = array_values(
+			array_filter(
+				token_get_all($code_str),
+				function ($token) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
				function ( $token ) {
```

File: src/Dist_Archive_Command.php [hunk 9]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 * The version tag might be specified as @version x.y.z or Version: x.y.z and it might be preceeded by an *
+	 *
+	 * @param string $code_str the source code string to look into
+	 * @return null|string the version string
+	 */
+	private static function get_version_in_code($code_str)
+	{
+		$tokens = array_values(
+			array_filter(
+				token_get_all($code_str),
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
				token_get_all( $code_str ),
```

File: src/Dist_Archive_Command.php [hunk 10]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+
+	/**
+	 * Gets the content of a version tag in any doc block in the given source code string
+	 *
+	 * The version tag might be specified as @version x.y.z or Version: x.y.z and it might be preceeded by an *
+	 *
+	 * @param string $code_str the source code string to look into
+	 * @return null|string the version string
+	 */
+	private static function get_version_in_code($code_str)
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	private static function get_version_in_code( $code_str )
```

File: src/Dist_Archive_Command.php [hunk 11]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+			array_filter(
+				token_get_all($code_str),
+				function ($token) {
+					return !is_array($token) || $token[0] !== T_WHITESPACE;
+				}
+			)
+		);
+		foreach ( $tokens as $token ) {
+			if ( $token[0] == T_DOC_COMMENT	) {
+				$version = self::get_version_in_docblock($token[1]);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
				$version = self::get_version_in_docblock( $token[1] );
```

File: src/Dist_Archive_Command.php [hunk 12]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+				if ( null !== $version ) {
+					return $version;
+				}
+			}
+		}
+		return null;
+	}
+
+	/**
+	 * Gets the content of a version tag in a docblock
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * Gets the content of a version tag in a docblock.
```

File: src/Dist_Archive_Command.php [hunk 13]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * @param string $docblock
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @param string $docblock Docblock to parse.
```

File: src/Dist_Archive_Command.php [hunk 14]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 * @return null|string The content of the version tag
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @return null|string The content of the version tag.
```

File: src/Dist_Archive_Command.php [hunk 15]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	*/
+	private static function get_version_in_docblock($docblock)
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	private static function get_version_in_docblock( $docblock )
```

File: src/Dist_Archive_Command.php [hunk 16]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	{
+		$docblocktags = self::parse_doc_block($docblock);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		$docblocktags = self::parse_doc_block( $docblock );
```

File: src/Dist_Archive_Command.php [hunk 17]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		if ( isset($docblocktags['version'] ) ) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		if ( isset( $docblocktags['version'] ) ) {
```

File: src/Dist_Archive_Command.php [hunk 18]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+			return $docblocktags['version'];
+		}
+		return null;
+	}
+
+	/**
+	 * Parses a docblock and gets an array of tags with their values
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * Parses a docblock and gets an array of tags with their values.
```

File: src/Dist_Archive_Command.php [hunk 19]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * The tags might be specified as @version x.y.z or Version: x.y.z and they might be preceeded by an *
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * The tags might be specified as "@version x.y.z" or "Version: x.y.z" and they can
	 * be preceded by an asterisk (*).
```

File: src/Dist_Archive_Command.php [hunk 20]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * This code is based on the phpactor package, namely:
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * This code is based on the 'phpactor' package.
```

File: src/Dist_Archive_Command.php [hunk 21]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *    https://github.com/phpactor/docblock/blob/master/lib/Parser.php
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @see https://github.com/phpactor/docblock/blob/master/lib/Parser.php
```

File: src/Dist_Archive_Command.php [hunk 22]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 *
+	 * @param string $docblock
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @param string $docblock Docblock to parse.
```

File: src/Dist_Archive_Command.php [hunk 23]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	 * @return array
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
	 * @return array Associative array of parsed data.
```

File: src/Dist_Archive_Command.php [hunk 24]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	*/
+	private static function parse_doc_block($docblock): array
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]: No return type hints, we're still supporting PHP 5.4.
```suggestion
	private static function parse_doc_block( $docblock )
```

File: src/Dist_Archive_Command.php [hunk 25]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+	{
+		$tag_documentor = '{@([a-zA-Z0-9-_\\\]+)\s*?(.*)?}';
+		$tag_property = '{\s*\*?\s*(.*?)\:(.*)}';
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		$tag_property   = '{\s*\*?\s*(.*?)\:(.*)}';
```

File: src/Dist_Archive_Command.php [hunk 26]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		$lines = explode(PHP_EOL, $docblock);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		$lines          = explode(PHP_EOL, $docblock);
```

File: src/Dist_Archive_Command.php [hunk 27]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		$tags = [];
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		$tags           = [];
```

File: src/Dist_Archive_Command.php [hunk 28]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		$prose = [];
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		$prose          = [];
```

File: src/Dist_Archive_Command.php [hunk 29]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		foreach ($lines as $line) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
		foreach ( $lines as $line ) {
```

File: src/Dist_Archive_Command.php [hunk 30]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+			if (0 === preg_match($tag_documentor, $line, $matches)) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			if ( 0 === preg_match( $tag_documentor, $line, $matches ) ) {
```

File: src/Dist_Archive_Command.php [hunk 31]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+				if (0 === preg_match($tag_property, $line, $matches)) {
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
				if ( 0 === preg_match( $tag_property, $line, $matches ) ) {
```

File: src/Dist_Archive_Command.php [hunk 32]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+					continue;
+				}
+			}
+			$tagName = strtolower($matches[1]);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			$tag_name          = strtolower( $matches[1] );
```

File: src/Dist_Archive_Command.php [hunk 33]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+			$metadata = trim($matches[2] ?? '');
+			$tags[$tagName] = $metadata;
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			$tags[ $tag_name ] = $metadata;
```

File: src/Dist_Archive_Command.php [hunk 34]
```diff
@@ -174,4 +175,80 @@ private function maybe_create_directory( $archive_file ) {
...
+		$tags = [];
+		$prose = [];
+		foreach ($lines as $line) {
+			if (0 === preg_match($tag_documentor, $line, $matches)) {
+				if (0 === preg_match($tag_property, $line, $matches)) {
+					continue;
+				}
+			}
+			$tagName = strtolower($matches[1]);
+			$metadata = trim($matches[2] ?? '');
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			$metadata          = isset( $matches[2] ) ? trim( $matches[2] ) : '';
```

File: src/Dist_Archive_Command.php [hunk 35]
```diff
@@ -92,8 +92,9 @@ public function __invoke( $args, $assoc_args ) {
 		$version = '';
 		foreach ( glob( $path . '/*.php' ) as $php_file ) {
 			$contents = file_get_contents( $php_file, false, null, 0, 5000 );
-			if ( preg_match( '#\* Version:(.+)#', $contents, $matches ) ) {
-				$version = '.' . trim( $matches[1] );
+			$version = $this->get_version_in_code($contents);
```
Comment (schlessera) [inline src/Dist_Archive_Command.php]:
```suggestion
			$version = $this->get_version_in_code( $contents );
```

**Comment by schlessera** [comment]
@santilin Are you still interested in working on this?

**Comment by schlessera** [comment]
Gentle ping? :D
